version: '3'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - "8080:8080"

#  redis:
#    container_name: redis
#    image: redis:latest
#    ports:
#      - "6379:6379"
