= API 문서
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

= 공통 권한

== 0. 인증

=== 보호소 로그인

==== Request

operation::auth-controller-test/shelter-login[snippets='http-request,request-fields']

==== Response

operation::auth-controller-test/shelter-login[snippets='http-response,response-fields,response-cookies']

=== 봉사자 로그인

==== Request

operation::auth-controller-test/volunteer-login[snippets='http-request,request-fields']

==== Response

operation::auth-controller-test/volunteer-login[snippets='http-response,response-fields,response-cookies']

=== 액세스 토큰 갱신

==== Request

operation::auth-controller-test/refresh-access-token[snippets='http-request,request-cookies']

==== Response

operation::auth-controller-test/refresh-access-token[snippets='http-response,response-fields,response-cookies']

== 1. 봉사자

=== 봉사자가 완료한 봉사 모집글 리스트 조회

==== Request

operation::recruitment-controller-test/find-completed-recruitments[snippets='http-request,path-parameters,query-parameters']

==== Response

operation::recruitment-controller-test/find-completed-recruitments[snippets='http-response,response-fields']

== 보호 동물

=== 보호 동물 상세 조회

==== Request

operation::animal-controller-test/find-animal-detail-test[snippets='http-request,path-parameters']

==== Response

operation::animal-controller-test/find-animal-detail-test[snippets='http-response,response-fields']

= 보호소

== 1. 봉사자

=== 1) 봉사 모집글 조회 & 검색

==== Request

operation::recruitment-controller-test/find-recruitments-by-volunteer[snippets='http-request,request-headers,query-parameters']

==== Response

operation::recruitment-controller-test/find-recruitments-by-volunteer[snippets='http-response,response-fields']

=== 보호소에 달린 후기 리스트 조회

==== Request

operation::review-controller-test/find-shelter-reviews-by-volunteer[snippets='http-request,path-parameters,query-parameters']

==== Response

operation::review-controller-test/find-shelter-reviews-by-volunteer[snippets='http-response,response-fields']

== 2. 보호소

=== 보호소 비밀번호 변경

==== Request
operation::shelter-controller-test/update-password[snippets='http-request,request-headers,request-fields']

==== Response
operation::shelter-controller-test/update-password[snippets='http-response']

=== 보호소 마이 페이지 조회

==== Request

operation::shelter-controller-test/find-shelter-my-page[snippets='http-request,request-headers']

==== Response

operation::shelter-controller-test/find-shelter-my-page[snippets='http-response,response-fields']

== 3. 봉사 모집

=== 1) 봉사 모집글 등록

==== Request

operation::recruitment-controller-test/register-recruitment[snippets='http-request,request-headers,request-fields']

==== Response

operation::recruitment-controller-test/register-recruitment[snippets='http-response,response-headers']

=== 봉사 모집글 마감

==== Request

operation::recruitment-controller-test/close-recruitment[snippets='http-request,request-headers,path-parameters']

==== Response

operation::recruitment-controller-test/close-recruitment[snippets='http-response']

=== 봉사 모집글 수정

==== Request

operation::recruitment-controller-test/update-recruitment[snippets='http-request,request-headers,path-parameters,request-fields']

==== Response

operation::recruitment-controller-test/update-recruitment[snippets='http-response']

== 4. 봉사 신청

== 5. 봉사 후기

== 6. 보호 동물

=== 보호 동물 삭제

==== Request

operation::animal-controller-test/delete-animal[snippets='http-request,request-headers,path-parameters']

==== Response

operation::animal-controller-test/delete-animal[snippets='http-response']

= 봉사자

== 1. 봉사자

=== 봉사자 계정 정보 수정

==== Request
operation::volunteer-controller-test/update-volunteer-info[snippets='http-request,request-headers,request-fields']

==== Response
operation::volunteer-controller-test/update-volunteer-info[snippets='http-response']

== 2. 보호소

== 3. 봉사 모집글

== 4. 봉사 신청

== 5. 봉사 후기

== 6. 보호 동물

= Enum 문서화

== 1. 보호 동물 성격

include::{snippets}/enum-documentation-test/animal-active/enum-response-fields.adoc[]

== 2. 보호 동물 성별

include::{snippets}/enum-documentation-test/animal-gender/enum-response-fields.adoc[]

== 3. 보호 동물 종류

include::{snippets}/enum-documentation-test/animal-type/enum-response-fields.adoc[]

== 4. 봉사 신청자 상태

include::{snippets}/enum-documentation-test/animal-type/enum-response-fields.adoc[]

== 5. 봉사자 성별

include::{snippets}/enum-documentation-test/animal-type/enum-response-fields.adoc[]